version: '3.8'

services:
  app:
    build: .
    container_name: app
    command: yarn dev
    tty: true
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      TZ: ${TZ}
    volumes:
      - .:/app
    ports:
      - '3000:3000'
      - '5555:5555'